version: '3'
 
volumes:
  elasticsearch:
    driver: local

services:
  messaging-api:
    build: ./messaging-service
    container_name: 'messaging-api'
    ports:
      - 5001:80 
    depends_on:
      - messaging-db
      - elasticsearch

  messaging-db:
    image: mongo
    container_name: 'messaging-db'
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - /home/barry/mongodb/database:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped  

  elasticsearch:
    container_name: 'elasticsearch'
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    
    ports:
    - 9200:9200
    restart: unless-stopped
    volumes:
    - elasticsearch:/usr/share/elasticsearch/data:rw

  kibana:
    container_name: 'kibana'
    depends_on:
    - elasticsearch
    environment:
      ELASTICSEARCH_PASSWORD: changeme
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
    image: docker.elastic.co/kibana/kibana-oss:6.2.1
     
    ports:
    - 5601:5601
    restart: unless-stopped